title: Foreign Agent Prototype # You will insert your title here.
email: your-email@example.com
description: by Authors Max Ellman, Anthony Lira-Ruelas, Max Polizzi # Author names go here.

baseurl: "/forgn_agnt" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
